# Generated by Django 6.1 on 2026-08-20 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelerins', '0006_pelerin_chambre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('resolue', 'Résolue'), ('fermee', 'Fermée')], default='nouvelle', max_length=15)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('reponse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['fondateur', 'admin_general', 'affaires_sociales']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations_creees', to=settings.AUTH_USER_MODEL)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='pelerins.pelerin')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
