# Generated by Django 6.1 on 2026-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(help_text='Doit correspondre exactement à la clé du menu frontend', max_length=50, unique=True)),
                ('nom_affiche', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Module du système',
                'verbose_name_plural': 'Modules du système',
                'ordering': ['ordre', 'nom_affiche'],
            },
        ),
    ]
