# Generated by Django 6.1 on 2026-08-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('beneficiaire_nom', models.CharField(help_text="Nom de la personne qui reçoit l'argent", max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(max_length=255)),
                ('date_sortie', models.DateField()),
                ('justifie', models.BooleanField(default=False, help_text="Coché une fois l'argent justifié ou remboursé")),
                ('date_justification', models.DateField(blank=True, null=True)),
                ('notes_justification', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire_utilisateur', models.ForeignKey(blank=True, help_text="Si c'est un employé du système, le sélectionner ici (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie_recus', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de sortie',
                'verbose_name_plural': 'Bons de sortie',
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('salaires', 'Salaires'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('communication', 'Communication'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date_depense', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='DetteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(help_text='Ex: Makkah Towers, Air Guinée', max_length=150)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(max_length=255)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('soldee', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes_fournisseur_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dette fournisseur',
                'verbose_name_plural': 'Dettes fournisseurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
