# Generated by Django 6.1 on 2026-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('general', 'Général (agence)')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('general', 'Général (agence)')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='dettefournisseur',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('general', 'Général (agence)')], default='general', max_length=20),
        ),
    ]
