# Generated by Django 6.1 on 2026-09-11 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_bonsortie_activite_depense_activite_and_more'),
        ('pelerins', '0012_pelerin_vehicule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('pourcentage_part', models.DecimalField(decimal_places=2, help_text='Ex: 30.00 pour 30%', max_digits=5)),
                ('est_caisse', models.BooleanField(default=False, help_text="Coché uniquement pour 'La caisse'")),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Associé',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='CategorieDecaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('personnel', 'Frais personnels (agence)')], max_length=15)),
                ('nom', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_categorie_fixe', models.BooleanField(default=True, help_text="False pour les catégories ajoutées librement par l'agence")),
            ],
            options={
                'verbose_name': 'Catégorie de décaissement',
                'verbose_name_plural': 'Catégories de décaissement',
                'ordering': ['activite', 'ordre'],
                'unique_together': {('activite', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Creance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('SAR', 'Riyal Saoudien')], default='GNF', max_length=3)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire')], max_length=20)),
                ('soldee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creances_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('personnel', 'Frais personnels (agence)')], max_length=15)),
                ('libelle_complementaire', models.CharField(blank=True, help_text='Précision, ex: période concernée', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('SAR', 'Riyal Saoudien')], default='GNF', max_length=3)),
                ('date_decaissement', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decaissements', to='comptabilite.categoriedecaissement')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decaissements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('pelerin', models.ForeignKey(blank=True, help_text='Si cette dépense concerne un pèlerin précis (pour Bénéfices par pèlerin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decaissements_lies', to='pelerins.pelerin')),
            ],
            options={
                'verbose_name': 'Décaissement',
                'verbose_name_plural': 'Décaissements',
                'ordering': ['-date_decaissement'],
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('SAR', 'Riyal Saoudien')], default='GNF', max_length=3)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire')], max_length=20)),
                ('soldee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dette',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DevisFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture'), ('avoir', 'Avoir')], max_length=10)),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('client_nom', models.CharField(blank=True, help_text='Si pas lié à un pèlerin', max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('SAR', 'Riyal Saoudien')], default='GNF', max_length=3)),
                ('date_emission', models.DateField()),
                ('paye', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_factures_enregistres', to=settings.AUTH_USER_MODEL)),
                ('pelerin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_factures', to='pelerins.pelerin')),
            ],
            options={
                'verbose_name': 'Devis / Facture',
                'ordering': ['-date_emission'],
            },
        ),
    ]
