# Generated by Django 6.1 on 2026-09-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_associe_categoriedecaissement_creance_decaissement_and_more'),
    ]

    operations = [
    ]
