# Generated by Django 6.1 on 2026-09-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_seed_categories_decaissement'),
    ]

    operations = [
    ]
