# Generated by Django 6.1 on 2026-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_seed_associes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_usd', models.DecimalField(decimal_places=2, help_text='Nombre de GNF pour 1 USD', max_digits=10)),
                ('taux_sar', models.DecimalField(decimal_places=2, help_text='Nombre de GNF pour 1 SAR', max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taux de change',
            },
        ),
    ]
