# Generated by Django 6.1 on 2026-09-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_tauxchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisonComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Hajj 2027', max_length=100, unique=True)),
                ('activite', models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('personnel', 'Frais personnels (agence)')], max_length=15)),
                ('date_debut', models.DateField(help_text="Début réel de l'exercice, peut être en fin d'année précédente")),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=True, help_text="La saison actuellement en cours d'utilisation")),
            ],
            options={
                'verbose_name': 'Saison comptable',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='decaissement',
            name='saison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decaissements', to='comptabilite.saisoncomptable'),
        ),
    ]
