# Generated by Django 6.1 on 2026-09-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_saisoncomptable_decaissement_saison'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationBeneficeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('saison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation_benefice', to='comptabilite.saisoncomptable')),
            ],
            options={
                'verbose_name': 'Observation Bénéfice Global',
            },
        ),
    ]
