# Generated by Django 6.1 on 2026-09-15 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0008_observationbeneficeglobal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dette',
            name='associe',
            field=models.ForeignKey(blank=True, help_text='Si cette dette concerne un des associés (pour Bénéfices Individuels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettes', to='comptabilite.associe'),
        ),
        migrations.AlterField(
            model_name='dette',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes_personnelles_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
    ]
