# Generated by Django 6.1 on 2026-09-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_dette_associe_alter_dette_enregistre_par'),
        ('pelerins', '0012_pelerin_vehicule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensePelerin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('charges_communes', 'Charges communes'), ('iban', 'Charges particulières IBAN'), ('consulat', 'Charges particulières CONSULAT'), ('transport_mounazim', 'Transport Mounazim'), ('prime_mounazim', 'Prime Mounazim'), ('scan_passeport', 'Scan passeport pour Visa'), ('frais_docteur', 'Frais docteur'), ('medicaments', 'Frais médicaments pèlerins'), ('unapo', 'Cotisation UNAPO'), ('dnp', 'Frais DNP'), ('mouton', 'Frais mouton'), ('difference_taux', "Différence de taux d'échange"), ('envoi_consulat', "Frais d'envoi au consulat"), ('prime_guide', 'Prime Guide'), ('depenses_personnelles', 'Dépenses personnelles'), ('autre', 'Autres dépenses')], max_length=30)),
                ('libelle_complementaire', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('SAR', 'Riyal Saoudien')], default='GNF', max_length=3)),
                ('date', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_pelerin_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_individuelles', to='pelerins.pelerin')),
            ],
            options={
                'verbose_name': 'Dépense par pèlerin',
                'ordering': ['-date'],
            },
        ),
    ]
