# Generated by Django 6.1 on 2026-09-25 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0010_depensepelerin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBudgetFonctionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('montant_entree', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_budget_fonctionnement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ligne budget de fonctionnement',
                'ordering': ['date_creation'],
            },
        ),
    ]
