# Generated by Django 6.1 on 2026-09-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_lignebudgetfonctionnement'),
        ('pelerins', '0012_pelerin_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensepelerin',
            name='pelerin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses_individuelles', to='pelerins.pelerin'),
        ),
    ]
