# Generated by Django 6.1 on 2026-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_alter_depensepelerin_pelerin'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisfacture',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('personnel', 'Frais personnels (agence)')], default='hajj', max_length=15),
        ),
        migrations.AddField(
            model_name='lignebudgetfonctionnement',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('personnel', 'Frais personnels (agence)')], default='hajj', max_length=15),
        ),
    ]
