# Generated by Django 6.1 on 2026-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0014_dette_activite_creance_activite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dette',
            name='activite',
        ),
        migrations.AlterField(
            model_name='creance',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra'), ('personnel', 'Frais personnels (agence)')], default='hajj', max_length=15),
        ),
    ]
