# Generated by Django 6.1 on 2026-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0015_remove_dette_activite_alter_creance_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creance',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra')], default='hajj', max_length=10),
        ),
        migrations.AlterField(
            model_name='dettefournisseur',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra')], default='hajj', max_length=10),
        ),
    ]
