# Generated by Django 6.1 on 2026-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0017_dette_activite_alter_creance_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='associe',
            name='activite',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra', 'Oumra')], default='hajj', max_length=10),
        ),
        migrations.AlterField(
            model_name='associe',
            name='pourcentage_part',
            field=models.DecimalField(decimal_places=2, help_text='Ex: 30.00 pour 30%. Ignoré pour Oumra (calculé selon les inscriptions)', max_digits=5),
        ),
    ]
