# Generated by Django 6.1 on 2026-08-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('attestation_inscription', "Attestation d'inscription"), ('attestation_paiement', 'Attestation de paiement'), ('contrat', 'Contrat de prestation'), ('attestation_sante', 'Attestation de santé')], max_length=30, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('corps_html', models.TextField(help_text='Contenu du document. Utilisez {{ p.prenom }}, {{ p.nom }}, {{ p.numero_id }}, {{ p.numero_passeport }}, {{ p.montant_total_verse }}, {{ aujourdhui }}, etc. Pour les paiements, utilisez {% for paiement in paiements %}...{% endfor %}.')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
            },
        ),
    ]
