# Generated by Django 6.1 on 2026-08-17 15:55

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelerins', '0004_pelerin_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='N° de transaction (Orange Money / virement)', max_length=100)),
                ('date_paiement', models.DateField()),
                ('scan_recu', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='paiements/recus/')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='pelerins.pelerin')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
    ]
