# Generated by Django 6.1 on 2026-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4, unique=True)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_suppression',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_recu',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
