# Generated by Django 6.1 on 2026-09-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_saisoncomptable_decaissement_saison'),
        ('paiements', '0002_sequencerecu_paiement_motif_suppression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='saison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='comptabilite.saisoncomptable'),
        ),
    ]
