# Generated by Django 6.1 on 2026-08-20 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formules', '0003_rename_prix_double_programme_prix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(max_length=100)),
                ('numero_vol', models.CharField(max_length=20)),
                ('date_vol', models.DateField()),
                ('heure_vol', models.TimeField()),
                ('aeroport_depart', models.CharField(max_length=100)),
                ('aeroport_arrivee', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vol',
                'verbose_name_plural': 'Vols',
                'ordering': ['date_vol', 'heure_vol'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('encadreur', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['guide', 'encadreur', 'mounazim']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_encadres', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='formules.programme')),
                ('vol_aller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_aller', to='groupes_vols.vol')),
                ('vol_retour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_retour', to='groupes_vols.vol')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
