# Generated by Django 6.1 on 2026-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='bagages_autorises_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Poids autorisé par pèlerin, en kg', null=True),
        ),
        migrations.AddField(
            model_name='vol',
            name='numero_billet_reference',
            field=models.CharField(blank=True, help_text='Référence de réservation groupe (PNR)', max_length=100),
        ),
    ]
