# Generated by Django 6.1 on 2026-09-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0002_vol_bagages_autorises_kg_vol_numero_billet_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='type_vol',
            field=models.CharField(choices=[('aller', 'Aller'), ('retour', 'Retour')], default='aller', max_length=10),
        ),
    ]
