# Generated by Django 6.1 on 2026-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0003_vol_type_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='capacite_max',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximum de pèlerins pour ce groupe', null=True),
        ),
    ]
