# Generated by Django 6.1 on 2026-09-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0004_groupe_capacite_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='encadreur',
            field=models.CharField(blank=True, default='change', help_text='Nom du guide/encadreur (saisie libre)', max_length=150),
            preserve_default=False,
        ),
    ]
