# Generated by Django 6.1 on 2026-09-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0005_alter_groupe_encadreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='responsable_medical',
            field=models.CharField(blank=True, help_text='Nom du médecin/responsable médical (saisie libre)', max_length=150),
        ),
    ]
