# Generated by Django 6.1 on 2026-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0006_groupe_responsable_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bus', models.CharField(help_text='Numéro ou nom du bus (ex: Bus 01)', max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('voiture', 'Voiture'), ('autre', 'Autre')], default='bus', max_length=15)),
                ('plaque_immatriculation', models.CharField(blank=True, max_length=30)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('chauffeur', models.CharField(blank=True, help_text='Nom du chauffeur (saisie libre)', max_length=150)),
                ('telephone_chauffeur', models.CharField(blank=True, max_length=20)),
                ('trajet', models.CharField(blank=True, help_text='Ex: Hôtel Makkah → Haram', max_length=255)),
                ('date_debut_utilisation', models.DateField(blank=True, null=True)),
                ('date_fin_utilisation', models.DateField(blank=True, null=True)),
                ('cout_location', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['numero_bus'],
            },
        ),
    ]
