# Generated by Django 6.1 on 2026-09-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0007_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='groupe_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_lies', to='groupes_vols.groupe'),
        ),
    ]
