# Generated by Django 6.1 on 2026-08-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(choices=[('mecque', 'Mecque'), ('medine', 'Médine')], max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_debut_sejour', models.DateField(blank=True, null=True)),
                ('date_fin_sejour', models.DateField(blank=True, null=True)),
                ('cout_contrat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('type_chambre', models.CharField(choices=[('individuelle', 'Individuelle'), ('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple')], max_length=15)),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hebergement.hotel')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['numero'],
                'unique_together': {('hotel', 'numero')},
            },
        ),
    ]
