# Generated by Django 6.1 on 2026-09-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='hebergement.ville'),
        ),
    ]
