# Generated by Django 6.1 on 2026-09-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0002_ville_alter_hotel_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='categorie',
            field=models.CharField(blank=True, choices=[('economique', 'Économique'), ('standard', 'Standard'), ('superieur', 'Supérieur'), ('luxe', 'Luxe')], max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='distance_haram_metres',
            field=models.PositiveIntegerField(blank=True, help_text='Distance du Haram en mètres', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nombre_chambres_prevu',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de chambres réservées (prévisionnel)', null=True),
        ),
        migrations.CreateModel(
            name='Campement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tente_camp', models.CharField(help_text='Numéro ou nom de la tente/camp (ex: T-12A)', max_length=50)),
                ('groupe', models.CharField(blank=True, help_text='Nom du groupe affecté', max_length=100)),
                ('zone', models.CharField(blank=True, help_text='Zone du site (ex: Zone 3, Secteur B)', max_length=100)),
                ('affectation', models.CharField(blank=True, help_text="Détail d'affectation libre", max_length=150)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campements', to='hebergement.ville')),
            ],
            options={
                'verbose_name': 'Campement',
                'verbose_name_plural': 'Campements',
                'ordering': ['ville', 'tente_camp'],
            },
        ),
    ]
