# Generated by Django 6.1 on 2026-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0003_hotel_categorie_hotel_distance_haram_metres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='type_chambre',
            field=models.CharField(choices=[('individuelle', 'Individuelle'), ('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple'), ('quintuple', 'Quintuple'), ('sextuple', 'Sextuple')], max_length=15),
        ),
    ]
