# Generated by Django 6.1 on 2026-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_programme', models.CharField(choices=[('hajj', 'Hajj'), ('oumra_ramadan', 'Oumra Ramadan'), ('oumra_classique', 'Oumra classique')], max_length=20)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('capacite_max', models.IntegerField()),
                ('prix_double', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_triple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_quadruple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
    ]
