# Generated by Django 6.1 on 2026-08-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='date_limite_paiement',
            field=models.DateField(blank=True, help_text='Date à laquelle le solde doit être intégralement payé', null=True),
        ),
    ]
