# Generated by Django 6.1 on 2026-08-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formules', '0002_programme_date_limite_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='prix_double',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='capacite_max',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='prix_quadruple',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='prix_triple',
        ),
    ]
