# Generated by Django 6.1 on 2026-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formules', '0003_rename_prix_double_programme_prix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['-annee', '-date_depart'], 'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AddField(
            model_name='programme',
            name='annee',
            field=models.PositiveIntegerField(default=2026, help_text='Année de la campagne (ex: 2024)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='est_archive',
            field=models.BooleanField(default=False, help_text="Un programme archivé n'apparaît plus dans les alertes de paiement/documents — utile pour les campagnes des années précédentes."),
        ),
    ]
