# Generated by Django 6.1 on 2026-09-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formules', '0004_alter_programme_options_programme_annee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_voyage', models.CharField(choices=[('pelerinage', 'Hajj'), ('oumra', 'Oumra')], max_length=20)),
                ('standard', models.CharField(choices=[('vip', 'VIP'), ('semi_vip', 'Semi-VIP'), ('standard', 'Standard')], max_length=20)),
                ('annee', models.PositiveIntegerField()),
                ('prix_vente', models.PositiveBigIntegerField(help_text='En francs guinéens (GNF), chiffre uniquement')),
                ('cout_reel', models.PositiveBigIntegerField(help_text='En francs guinéens (GNF), chiffre uniquement')),
                ('nombre_places', models.PositiveIntegerField()),
                ('services_inclus', models.TextField(blank=True, help_text='Un service par ligne')),
                ('services_exclus', models.TextField(blank=True, help_text='Un service par ligne')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'ordering': ['-annee', 'type_voyage', 'standard'],
            },
        ),
    ]
