# Generated by Django 6.1 on 2026-09-01 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formules', '0005_forfait'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('montant', models.PositiveBigIntegerField(default=0, help_text='En GNF, chiffre uniquement')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='formules.forfait')),
            ],
            options={
                'verbose_name': 'Ligne de prestation',
                'verbose_name_plural': 'Lignes de prestations',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
