# Generated by Django 6.1 on 2026-10-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formules', '0006_ligneforfait'),
        ('hebergement', '0005_hotel_campement_type_voyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='nombre_max_pelerins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='planning_valide',
            field=models.BooleanField(default=False, help_text='Le planning validé peut être exporté en PDF'),
        ),
        migrations.AddField(
            model_name='programme',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='responsable',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='programme',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert aux inscriptions'), ('complet', 'Complet'), ('cloture', 'Clôturé'), ('archive', 'Archivé')], default='ouvert', max_length=15),
        ),
        migrations.AlterField(
            model_name='programme',
            name='type_programme',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('oumra_ramadan', 'Oumra Ramadan'), ('oumra_classique', 'Oumra classique'), ('oumra_speciale', 'Oumra spéciale')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivitePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('activite', models.CharField(max_length=200)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='formules.programme')),
            ],
            options={
                'verbose_name': 'Activité du planning',
                'verbose_name_plural': 'Activités du planning',
                'ordering': ['date', 'heure', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SejourProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(choices=[('makkah', 'Makkah'), ('medine', 'Médine')], max_length=10)),
                ('hotel_nom', models.CharField(blank=True, max_length=150)),
                ('hotel_adresse', models.CharField(blank=True, max_length=255)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('distance_haram_metres', models.PositiveIntegerField(blank=True, help_text='Distance de la Mosquée sacrée', null=True)),
                ('type_chambre', models.CharField(blank=True, choices=[('individuelle', 'Individuelle'), ('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple'), ('quintuple', 'Quintuple'), ('sextuple', 'Sextuple')], max_length=15)),
                ('capacite_chambre', models.PositiveIntegerField(blank=True, null=True)),
                ('repas_inclus', models.TextField(blank=True)),
                ('prestations_incluses', models.TextField(blank=True)),
                ('visites_ziyarat', models.TextField(blank=True)),
                ('activites_religieuses', models.TextField(blank=True)),
                ('transport', models.CharField(blank=True, max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours_programmes', to='hebergement.hotel')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sejours', to='formules.programme')),
            ],
            options={
                'verbose_name': 'Séjour de programme',
                'verbose_name_plural': 'Séjours de programme',
                'ordering': ['date_arrivee', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransportProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_trajet', models.CharField(choices=[('aeroport_hotel', 'Aéroport → hôtel'), ('makkah_medine', 'Makkah → Médine'), ('medine_aeroport', 'Médine → aéroport'), ('autre', 'Autre')], max_length=20)),
                ('type_vehicule', models.CharField(blank=True, max_length=100)),
                ('prestataire', models.CharField(blank=True, max_length=150)),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
                ('nombre_pelerins', models.PositiveIntegerField(blank=True, null=True)),
                ('chauffeur_nom', models.CharField(blank=True, max_length=150)),
                ('chauffeur_contact', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=15)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='formules.programme')),
            ],
            options={
                'verbose_name': 'Transport de programme',
                'verbose_name_plural': 'Transports de programme',
                'ordering': ['date_heure', 'id'],
            },
        ),
    ]
