import api from "./api";
import CONFIG from "../config/config";

export const decaissementService = {
  listerCategories: (activite) => api.get(CONFIG.API_CATEGORIES_DECAISSEMENT, { params: { activite } }),
  creerCategorie: (donnees) => api.post(CONFIG.API_CATEGORIES_DECAISSEMENT, donnees),
  lister: (params) => api.get(CONFIG.API_DECAISSEMENTS, { params }),
  creer: (donnees) => api.post(CONFIG.API_DECAISSEMENTS, donnees),
  modifier: (id, donnees) => api.patch(CONFIG.API_DECAISSEMENT_DETAIL(id), donnees),
  supprimer: (id) => api.delete(CONFIG.API_DECAISSEMENT_DETAIL(id)),
  listerAnneesDisponibles: () => api.get(`${CONFIG.API_DECAISSEMENTS}annees-disponibles/`),
  obtenirRecapitulatif: (activite, annee) => api.get(`${CONFIG.API_DECAISSEMENTS}recapitulatif/`, { params: { activite, annee } }),
  obtenirTauxChange: () => api.get(CONFIG.API_TAUX_CHANGE),
  modifierTauxChange: (donnees) => api.patch(CONFIG.API_TAUX_CHANGE, donnees),
  listerSaisons: (activite) => api.get(CONFIG.API_SAISONS, { params: { activite } }),
  creerSaison: (donnees) => api.post(CONFIG.API_SAISONS, donnees),
  obtenirHistoriqueDecaissement: (id) => api.get(`${CONFIG.API_DECAISSEMENT_DETAIL(id)}historique/`),
  listerSaisons: (activite) => api.get(CONFIG.API_SAISONS, { params: { activite } }),
  creerSaison: (donnees) => api.post(CONFIG.API_SAISONS, donnees),
  obtenirRecapitulatif: (activite, annee, saison) => api.get(`${CONFIG.API_DECAISSEMENTS}recapitulatif/`, { params: { activite, saison } }),
  obtenirHistoriqueDecaissement: (id) => api.get(`${CONFIG.API_DECAISSEMENT_DETAIL(id)}historique/`),
  obtenirEncaissements: (activite) => api.get(CONFIG.API_ENCAISSEMENTS, { params: { activite } }),
  obtenirBeneficeGlobal: (activite, saison) => api.get(CONFIG.API_BENEFICE_GLOBAL, { params: { activite, saison } }),
  enregistrerObservationBeneficeGlobal: (saison, observation) => api.patch(CONFIG.API_BENEFICE_GLOBAL, { saison, observation }),
  listerDettes: (params) => api.get(CONFIG.API_DETTES, { params }),
  creerDette: (donnees) => api.post(CONFIG.API_DETTES, donnees),
  modifierDette: (id, donnees) => api.patch(CONFIG.API_DETTE_DETAIL(id), donnees),
  supprimerDette: (id) => api.delete(CONFIG.API_DETTE_DETAIL(id)),
  listerAssocies: () => api.get(CONFIG.API_ASSOCIES),
  obtenirBeneficeIndividuel: (activite, saison) => api.get(CONFIG.API_BENEFICE_INDIVIDUEL, { params: { activite, saison } }),
  listerDepensesPelerin: (pelerinId) => api.get(CONFIG.API_DEPENSES_PELERIN, { params: { pelerin: pelerinId } }),
  creerDepensePelerin: (donnees) => api.post(CONFIG.API_DEPENSES_PELERIN, donnees),
  supprimerDepensePelerin: (id) => api.delete(`${CONFIG.API_DEPENSES_PELERIN}${id}/`),
  obtenirRecapPelerin: (pelerinId) => api.get(`${CONFIG.API_DEPENSES_PELERIN}recapitulatif-pelerin/`, { params: { pelerin: pelerinId } }),


  listerCreances: (params) => api.get(CONFIG.API_CREANCES, { params }),
  creerCreance: (donnees) => api.post(CONFIG.API_CREANCES, donnees),
  modifierCreance: (id, donnees) => api.patch(CONFIG.API_CREANCE_DETAIL(id), donnees),
  supprimerCreance: (id) => api.delete(CONFIG.API_CREANCE_DETAIL(id)),

  listerDevisFactures: (params) => api.get(CONFIG.API_DEVIS_FACTURES, { params }),
  creerDevisFacture: (donnees) => api.post(CONFIG.API_DEVIS_FACTURES, donnees),
  modifierDevisFacture: (id, donnees) => api.patch(CONFIG.API_DEVIS_FACTURE_DETAIL(id), donnees),
  supprimerDevisFacture: (id) => api.delete(CONFIG.API_DEVIS_FACTURE_DETAIL(id)),
  obtenirImpayes: () => api.get(`${CONFIG.API_DEVIS_FACTURES}impayes/`),
  listerBudgetFonctionnement: () => api.get(CONFIG.API_BUDGET_FONCTIONNEMENT),
  creerLigneBudget: (donnees) => api.post(CONFIG.API_BUDGET_FONCTIONNEMENT, donnees),
  modifierLigneBudget: (id, donnees) => api.patch(CONFIG.API_BUDGET_FONCTIONNEMENT_DETAIL(id), donnees),
  supprimerLigneBudget: (id) => api.delete(CONFIG.API_BUDGET_FONCTIONNEMENT_DETAIL(id)),
  obtenirRecapBudget: () => api.get(`${CONFIG.API_BUDGET_FONCTIONNEMENT}recapitulatif/`),
};