# Generated by Django 6.1 on 2026-08-25 19:12

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('numero_piece_identite', models.CharField(blank=True, max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('langues_parlees', models.CharField(blank=True, help_text='Séparées par des virgules', max_length=255)),
                ('nombre_saisons_experience', models.PositiveIntegerField(default=0)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=150)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20)),
                ('disponibilite', models.CharField(choices=[('actif', 'Actif cette saison'), ('conge', 'En congé'), ('indisponible', 'Indisponible')], default='actif', max_length=20)),
                ('scan_cv', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='personnel/cv/')),
                ('specialite_medicale', models.CharField(blank=True, max_length=150)),
                ('numero_ordre_medecins', models.CharField(blank=True, max_length=50)),
                ('etablissement_exercice', models.CharField(blank=True, max_length=150)),
                ('formation_religieuse', models.CharField(blank=True, max_length=255)),
                ('zone_competence', models.CharField(blank=True, choices=[('mecque', 'Mecque'), ('medine', 'Médine'), ('les_deux', 'Les deux')], max_length=15)),
                ('zone_affectation', models.CharField(blank=True, choices=[('mecque', 'Mecque'), ('medine', 'Médine'), ('transport', 'Transport'), ('aeroport', 'Aéroport')], max_length=15)),
                ('capacite_max_pelerins', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role__in': ['guide', 'encadreur', 'docteur', 'mounazim']}, on_delete=django.db.models.deletion.CASCADE, related_name='fiche_personnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche personnel',
                'verbose_name_plural': 'Fiches personnel',
            },
        ),
    ]
