# Generated by Django 6.1 on 2026-08-13 18:50

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelerin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pelerins/photos/')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=150)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20)),
                ('numero_passeport', models.CharField(blank=True, max_length=30)),
                ('date_expiration_passeport', models.DateField(blank=True, null=True)),
                ('scan_passeport', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pelerins/passeports/')),
                ('statut_visa', models.CharField(choices=[('non_demande', 'Non demandé'), ('en_cours', 'En cours (Nusuk)'), ('obtenu', 'Obtenu'), ('refuse', 'Refusé')], default='non_demande', max_length=20)),
                ('certificat_vaccination', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pelerins/vaccination/')),
                ('date_expiration_vaccination', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_preparation', 'En préparation'), ('valide', 'Validé'), ('en_voyage', 'En voyage'), ('retourne', 'Retourné'), ('cloture', 'Clôturé')], default='inscrit', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelerins', to='formules.programme')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_pelerin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pèlerin',
                'verbose_name_plural': 'Pèlerins',
            },
        ),
    ]
