# Generated by Django 6.1 on 2026-08-14 00:00

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4, unique=True)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pelerin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('numero_passeport', models.CharField(max_length=30)),
                ('date_emission_passeport', models.DateField()),
                ('date_expiration_passeport', models.DateField()),
                ('scan_passeport', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pelerins/passeports/')),
                ('statut_visa', models.CharField(choices=[('non_demande', 'Non demandé'), ('en_cours', 'En cours (Nusuk)'), ('obtenu', 'Obtenu'), ('refuse', 'Refusé')], default='non_demande', max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('nom_pere', models.CharField(blank=True, max_length=150, verbose_name='Nom du père')),
                ('nom_mere', models.CharField(blank=True, max_length=150, verbose_name='Nom de la mère')),
                ('montant_verse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scan_recu_versement', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pelerins/recus/')),
                ('nom_correspondant', models.CharField(max_length=150)),
                ('telephone_correspondant', models.CharField(max_length=20)),
                ('agence_partenaire', models.CharField(blank=True, help_text="À remplir uniquement si le pèlerin vient d'une agence partenaire.", max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pelerins/photos/')),
                ('scan_certificat_medical', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pelerins/certificats_medicaux/')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('probleme_sante', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_preparation', 'En préparation'), ('valide', 'Validé'), ('en_voyage', 'En voyage'), ('retourne', 'Retourné'), ('cloture', 'Clôturé')], default='inscrit', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('inscripteur', models.ForeignKey(limit_choices_to={'role__in': ['fondateur', 'admin_general', 'secretaire', 'comptable']}, on_delete=django.db.models.deletion.PROTECT, related_name='pelerins_inscrits', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelerins', to='formules.programme')),
            ],
            options={
                'verbose_name': 'Pèlerin',
                'verbose_name_plural': 'Pèlerins',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
