# Generated by Django 6.1 on 2026-08-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='type_voyage',
            field=models.CharField(choices=[('pelerinage', 'Pèlerinage (Hajj)'), ('oumra', 'Omra'), ('tourisme', 'Tourisme')], default='pelerinage', max_length=20),
            preserve_default=False,
        ),
    ]
