# Generated by Django 6.1 on 2026-08-14 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0002_pelerin_type_voyage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelerin',
            name='inscripteur',
            field=models.ForeignKey(limit_choices_to={'role__in': ['fondateur', 'admin_general', 'secretaire', 'comptable', 'affaires_sociales']}, on_delete=django.db.models.deletion.PROTECT, related_name='pelerins_inscrits', to=settings.AUTH_USER_MODEL),
        ),
    ]
