# Generated by Django 6.1 on 2026-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0003_alter_pelerin_inscripteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire')], max_length=20),
        ),
    ]
