# Generated by Django 6.1 on 2026-08-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0001_initial'),
        ('pelerins', '0004_pelerin_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelerins', to='groupes_vols.groupe'),
        ),
    ]
