# Generated by Django 6.1 on 2026-08-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0001_initial'),
        ('pelerins', '0005_pelerin_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelerins', to='hebergement.chambre'),
        ),
    ]
