# Generated by Django 6.1 on 2026-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0006_pelerin_chambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelerin',
            name='inscripteur',
            field=models.CharField(blank=True, help_text="Nom de l'agent ayant inscrit ce pèlerin", max_length=150),
        ),
    ]
