# Generated by Django 6.1 on 2026-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0007_alter_pelerin_inscripteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelerin',
            name='inscripteur',
            field=models.CharField(blank=True, choices=[('Nfamba Kaba', 'Nfamba Kaba'), ('Laye Mady Diallo', 'Laye Mady Diallo'), ('Laye Abou Diallo', 'Laye Abou Diallo'), ('Nfamba Keïta', 'Nfamba Keïta'), ('Minata Mady', 'Minata Mady'), ('Boh Kabinet', 'Boh Kabinet'), ('Hadja Fatou Diallo', 'Hadja Fatou Diallo'), ('Hadja Fanta Oulen', 'Hadja Fanta Oulen')], max_length=50),
        ),
    ]
