# Generated by Django 6.1 on 2026-09-01 11:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0008_alter_pelerin_inscripteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='biometrie_effectuee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelerin',
            name='date_biometrie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelerin',
            name='scan_visa',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pelerins/visas/'),
        ),
        migrations.AlterField(
            model_name='pelerin',
            name='statut_visa',
            field=models.CharField(choices=[('non_demande', 'Non demandé'), ('en_cours', 'En cours'), ('obtenu', 'Obtenu'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='non_demande', max_length=20),
        ),
    ]
