# Generated by Django 6.1 on 2026-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0009_pelerin_biometrie_effectuee_pelerin_date_biometrie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='check_in_effectue',
            field=models.BooleanField(default=False),
        ),
    ]
