# Generated by Django 6.1 on 2026-09-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0003_hotel_categorie_hotel_distance_haram_metres_and_more'),
        ('pelerins', '0010_pelerin_check_in_effectue'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='campement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelerins', to='hebergement.campement'),
        ),
    ]
