# Generated by Django 6.1 on 2026-09-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes_vols', '0007_vehicule'),
        ('pelerins', '0011_pelerin_campement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelerins', to='groupes_vols.vehicule'),
        ),
    ]
