# Generated by Django 6.1 on 2026-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelerins', '0012_pelerin_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelerin',
            name='inscripteur',
            field=models.CharField(blank=True, choices=[('Nfamba Kaba', 'Nfamba Kaba'), ('Laye Mady Diallo', 'Laye Mady Diallo'), ('Laye Abou Diallo', 'Laye Abou Diallo'), ('Nfamba Keïta', 'Nfamba Keïta'), ('Minata Mady', 'Minata Mady'), ('Boh Kabinet', 'Boh Kabinet'), ('Hadja Fatou Diallo', 'Hadja Fatou Diallo'), ('Hadja Fanta Oulen', 'Hadja Fanta Oulen'), ('Mohamed Ahmed Diallo', 'Mohamed Ahmed Diallo'), ('Aboubacar Diallo', 'Aboubacar Diallo'), ("N'famba Ibrahima kaba", "N'famba Ibrahima kaba"), ("Sekou N'bah koita", "Sekou N'bah koita"), ('Souleymane Sacko', 'Souleymane Sacko'), ('Minata Mady kaba', 'Minata Mady kaba')], max_length=50),
        ),
    ]
